trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'MyBackendArchetypeVariables'

jobs:

- job: DeployParameters
  displayName: 'Deploy Parameters'

  steps:

  - task: CloudFormationCreateOrUpdateStack@1
    displayName: 'Create Parameters Stack'
    inputs:
      awsCredentials: 'AWSConnectionPipeline'
      regionName: '$(ApplicationRegionName)'
      stackName: '$(ApplicationEnvironment)-$(StackParametersName)'
      templateSource: 'file'
      templateFile: 'params/parameters.yaml'
      capabilities: 'CAPABILITY_NAMED_IAM'
      templateParametersSource: 'inline'
      s3BucketName: '$(InfraS3BucketName)'
      rollbackConfiguration: 'DISABLED'
      on_failure: 'DO_NOTHING'
      templateParameters: |
        [
          {
            "ParameterKey": "AppTag",
            "ParameterValue": "$(ApplicationAppTag)"
          },
          {
            "ParameterKey": "OwnerTag",
            "ParameterValue": "$(ApplicationOwnerTag)"
          },
          {
            "ParameterKey": "EnvironmentTag",
            "ParameterValue": "$(ApplicationEnvironmentTag)"
          },
          {
            "ParameterKey": "AppManagerCFNStackKeyTag",
            "ParameterValue": "$(ApplicationManagerCFNStackKeyTag)"
          }
        ]