AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for defining Secrets

Parameters:
  StackParametersName:
    Type: String
    Description: The name of the parameters stack
    Default: StackParametersName
  
  DBUserName:
    Type: String
    Description: The username of the database
    Default: DBUserName

  DBPassword:
    Type: String
    Description: The password of the database
    Default: DBPassword

Resources:
  
    DBUserNameSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: "DBUserName"
        Description: The username of the database
        SecretString: !Ref DBUserName
        Tags:
          - Key: App
            Value: 
              Fn::ImportValue:
                !Sub ${StackParametersName}-AppTag
          - Key: Owner
            Value: 
              Fn::ImportValue:
                !Sub ${StackParametersName}-OwnerTag
          # - Key: Environment
          #   Value: 
          #     Fn::ImportValue:
          #       !Sub ${StackParametersName}-EnvironmentTag
          - Key: AppManagerCFNStackKey
            Value: 
              Fn::ImportValue:
                !Sub ${StackParametersName}-AppManagerCFNStackKeyTag

    DBPasswordSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: "DBPassword"
        Description: The username of the database
        SecretString: !Ref DBUserName
        Tags:
          - Key: App
            Value: 
              Fn::ImportValue:
                !Sub ${StackParametersName}-AppTag
          - Key: Owner
            Value: 
              Fn::ImportValue:
                !Sub ${StackParametersName}-OwnerTag
          # - Key: Environment
          #   Value: 
          #     Fn::ImportValue:
          #       !Sub ${StackParametersName}-EnvironmentTag
          - Key: AppManagerCFNStackKey
            Value: 
              Fn::ImportValue:
                !Sub ${StackParametersName}-AppManagerCFNStackKeyTag



